import mock from '../mock'
import { paginateArray } from '../utils'

const data = [
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    category: "Korrie O'Crevy",
    parent_category: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    city: 'Krasnosilka',
    start_date: '09/23/2016',
    salary: '$23896.35',
    stock_qty: '61',
    experience: '1 Year',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 2,
    avatar: '1.jpg',
    category: 'Bailie Coulman',
    parent_category: 'VP Quality Control',
    email: 'bcoulman1@yolasite.com',
    city: 'Hinigaran',
    start_date: '05/20/2018',
    salary: '$13633.69',
    stock_qty: '63',
    experience: '3 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 3,
    avatar: '9.jpg',
    category: 'Stella Ganderton',
    parent_category: 'Operator',
    email: 'sganderton2@tuttocitta.it',
    city: 'Golcowa',
    start_date: '03/24/2018',
    salary: '$13076.28',
    stock_qty: '66',
    experience: '6 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 4,
    avatar: '10.jpg',
    category: 'Dorolice Crossman',
    parent_category: 'Cost Accountant',
    email: 'dcrossman3@google.co.jp',
    city: 'Paquera',
    start_date: '12/03/2017',
    salary: '$12336.17',
    stock_qty: '22',
    experience: '2 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 5,
    avatar: '',
    category: 'Harmonia Nisius',
    parent_category: 'Senior Cost Accountant',
    email: 'hnisius4@gnu.org',
    city: 'Lucan',
    start_date: '08/25/2017',
    salary: '$10909.52',
    stock_qty: '33',
    experience: '3 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 6,
    avatar: '',
    category: 'Genevra Honeywood',
    parent_category: 'Geologist',
    email: 'ghoneywood5@narod.ru',
    city: 'Maofan',
    start_date: '06/01/2017',
    salary: '$17803.80',
    stock_qty: '61',
    experience: '1 Year',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 7,
    avatar: '',
    category: 'Eileen Diehn',
    parent_category: 'Environmental Specialist',
    email: 'ediehn6@163.com',
    city: 'Lampuyang',
    start_date: '10/15/2017',
    salary: '$18991.67',
    stock_qty: '59',
    experience: '9 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 8,
    avatar: '9.jpg',
    category: 'Richardo Aldren',
    parent_category: 'Senior Sales Associate',
    email: 'raldren7@mtv.com',
    city: 'Skoghall',
    start_date: '11/05/2016',
    salary: '$19230.13',
    stock_qty: '55',
    experience: '5 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 9,
    avatar: '2.jpg',
    category: 'Allyson Moakler',
    parent_category: 'Safety Technician',
    email: 'amoakler8@shareasale.com',
    city: 'Mogilany',
    start_date: '12/29/2018',
    salary: '$11677.32',
    stock_qty: '39',
    experience: '9 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 10,
    avatar: '9.jpg',
    category: 'Merline Penhalewick',
    parent_category: 'Junior Executive',
    email: 'mpenhalewick9@php.net',
    city: 'Kanuma',
    start_date: '04/19/2019',
    salary: '$15939.52',
    stock_qty: '23',
    experience: '3 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 11,
    avatar: '',
    category: 'De Falloon',
    parent_category: 'Sales Representative',
    email: 'dfalloona@ifeng.com',
    city: 'Colima',
    start_date: '06/12/2018',
    salary: '$19252.12',
    stock_qty: '30',
    experience: '0 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 12,
    avatar: '',
    category: 'Cyrus Gornal',
    parent_category: 'Senior Sales Associate',
    email: 'cgornalb@fda.gov',
    city: 'Boro Utara',
    start_date: '12/09/2017',
    salary: '$16745.47',
    stock_qty: '22',
    experience: '2 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 13,
    avatar: '',
    category: 'Tallou Balf',
    parent_category: 'Staff Accountant',
    email: 'tbalfc@sina.com.cn',
    city: 'Siliana',
    start_date: '01/21/2016',
    salary: '$15488.53',
    stock_qty: '36',
    experience: '6 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 14,
    avatar: '',
    category: 'Othilia Extill',
    parent_category: 'Associate Professor',
    email: 'oextilld@theatlantic.com',
    city: 'Brzyska',
    start_date: '02/01/2016',
    salary: '$18442.34',
    stock_qty: '43',
    experience: '3 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 15,
    avatar: '',
    category: 'Wilmar Bourton',
    parent_category: 'Administrative Assistant',
    email: 'wbourtone@sakura.ne.jp',
    city: 'Bích Động',
    start_date: '04/25/2018',
    salary: '$13304.45',
    stock_qty: '19',
    experience: '9 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 16,
    avatar: '4.jpg',
    category: 'Robinson Brazenor',
    parent_category: 'General Manager',
    email: 'rbrazenorf@symantec.com',
    city: 'Gendiwu',
    start_date: '12/23/2017',
    salary: '$11953.08',
    stock_qty: '66',
    experience: '6 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 17,
    avatar: '',
    category: 'Nadia Bettenson',
    parent_category: 'Environmental Tech',
    email: 'nbettensong@joomla.org',
    city: 'Chabařovice',
    start_date: '07/11/2018',
    salary: '$20484.44',
    stock_qty: '64',
    experience: '4 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 18,
    avatar: '',
    category: 'Titus Hayne',
    parent_category: 'Web Designer',
    email: 'thayneh@kickstarter.com',
    city: 'Yangon',
    start_date: '05/25/2019',
    salary: '$16871.48',
    stock_qty: '59',
    experience: '9 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 19,
    avatar: '5.jpg',
    category: 'Roxie Huck',
    parent_category: 'Administrative Assistant',
    email: 'rhucki@ed.gov',
    city: 'Polýkastro',
    start_date: '04/04/2019',
    salary: '$19653.56',
    stock_qty: '41',
    experience: '1 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 20,
    avatar: '7.jpg',
    category: 'Latashia Lewtey',
    parent_category: 'Actuary',
    email: 'llewteyj@sun.com',
    city: 'Hougong',
    start_date: '08/03/2017',
    salary: '$18303.87',
    stock_qty: '35',
    experience: '5 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 21,
    avatar: '',
    category: 'Natalina Tyne',
    parent_category: 'Software Engineer',
    email: 'ntynek@merriam-webster.com',
    city: 'Yanguan',
    start_date: '03/16/2019',
    salary: '$15256.40',
    stock_qty: '30',
    experience: '0 Year',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 22,
    avatar: '',
    category: 'Faun Josefsen',
    parent_category: 'Analog Circuit Design manager',
    email: 'fjosefsenl@samsung.com',
    city: 'Wengyang',
    start_date: '07/08/2017',
    salary: '$11209.16',
    stock_qty: '40',
    experience: '0 Year',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 23,
    avatar: '9.jpg',
    category: 'Rosmunda Steed',
    parent_category: 'Assistant Media Planner',
    email: 'rsteedm@xing.com',
    city: 'Manzanares',
    start_date: '12/23/2017',
    salary: '$13778.34',
    stock_qty: '21',
    experience: '1 Year',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 24,
    avatar: '',
    category: 'Scott Jiran',
    parent_category: 'Graphic Designer',
    email: 'sjirann@simplemachines.org',
    city: 'Pinglin',
    start_date: '05/26/2016',
    salary: '$23081.71',
    stock_qty: '23',
    experience: '3 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 25,
    avatar: '',
    category: 'Carmita Medling',
    parent_category: 'Accountant',
    email: 'cmedlingo@hp.com',
    city: 'Bourges',
    start_date: '07/31/2019',
    salary: '$13602.24',
    stock_qty: '47',
    experience: '7 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 26,
    avatar: '2.jpg',
    category: 'Morgen Benes',
    parent_category: 'Senior Sales Associate',
    email: 'mbenesp@ted.com',
    city: 'Cà Mau',
    start_date: '04/10/2016',
    salary: '$16969.63',
    stock_qty: '42',
    experience: '2 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 27,
    avatar: '',
    category: 'Onfroi Doughton',
    parent_category: 'Civil Engineer',
    email: 'odoughtonq@aboutads.info',
    city: 'Utrecht (stad)',
    start_date: '09/29/2018',
    salary: '$23796.62',
    stock_qty: '28',
    experience: '8 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 28,
    avatar: '',
    category: 'Kliment McGinney',
    parent_category: 'Chief Design Engineer',
    email: 'kmcginneyr@paginegialle.it',
    city: 'Xiaocheng',
    start_date: '07/09/2018',
    salary: '$24027.81',
    stock_qty: '28',
    experience: '8 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 29,
    avatar: '',
    category: 'Devin Bridgland',
    parent_category: 'Tax Accountant',
    email: 'dbridglands@odnoklassniki.ru',
    city: 'Baoli',
    start_date: '07/17/2016',
    salary: '$13508.15',
    stock_qty: '48',
    experience: '8 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 30,
    avatar: '6.jpg',
    category: 'Gilbert McFade',
    parent_category: 'Biostatistician',
    email: 'gmcfadet@irs.gov',
    city: 'Deje',
    start_date: '08/28/2018',
    salary: '$21632.30',
    stock_qty: '20',
    experience: '0 Year',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 31,
    avatar: '',
    category: 'Teressa Bleakman',
    parent_category: 'Senior Editor',
    email: 'tbleakmanu@phpbb.com',
    city: 'Žebrák',
    start_date: '09/03/2016',
    salary: '$24875.41',
    stock_qty: '37',
    experience: '7 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 32,
    avatar: '',
    category: 'Marcelia Alleburton',
    parent_category: 'Safety Technician',
    email: 'malleburtonv@amazon.com',
    city: 'Basail',
    start_date: '06/02/2016',
    salary: '$23888.98',
    stock_qty: '53',
    experience: '3 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 33,
    avatar: '7.jpg',
    category: 'Aili De Coursey',
    parent_category: 'Environmental Specialist',
    email: 'adew@etsy.com',
    city: 'Łazy',
    start_date: '09/30/2016',
    salary: '$14082.44',
    stock_qty: '27',
    experience: '7 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 34,
    avatar: '6.jpg',
    category: 'Charlton Chatres',
    parent_category: 'Analyst Programmer',
    email: 'cchatresx@goo.gl',
    city: 'Reguengos de Monsaraz',
    start_date: '04/07/2016',
    salary: '$21386.52',
    stock_qty: '22',
    experience: '2 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 35,
    avatar: '1.jpg',
    category: 'Nat Hugonnet',
    parent_category: 'Financial Advisor',
    email: 'nhugonnety@wufoo.com',
    city: 'Pimentel',
    start_date: '09/11/2019',
    salary: '$13835.97',
    stock_qty: '46',
    experience: '6 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 36,
    avatar: '',
    category: 'Lorine Hearsum',
    parent_category: 'Payment Adjustment Coordinator',
    email: 'lhearsumz@google.co.uk',
    city: 'Shuiying',
    start_date: '03/05/2019',
    salary: '$22093.91',
    stock_qty: '47',
    experience: '7 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 37,
    avatar: '8.jpg',
    category: 'Sheila-kathryn Haborn',
    parent_category: 'Environmental Specialist',
    email: 'shaborn10@about.com',
    city: 'Lewolang',
    start_date: '11/10/2018',
    salary: '$24624.23',
    stock_qty: '51',
    experience: '1 Year',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 38,
    avatar: '3.jpg',
    category: 'Alma Harvatt',
    parent_category: 'Administrative Assistant',
    email: 'aharvatt11@addtoany.com',
    city: 'Ulundi',
    start_date: '11/04/2016',
    salary: '$21782.82',
    stock_qty: '41',
    experience: '1 Year',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 39,
    avatar: '2.jpg',
    category: 'Beatrix Longland',
    parent_category: 'VP Quality Control',
    email: 'blongland12@gizmodo.com',
    city: 'Damu',
    start_date: '07/18/2016',
    salary: '$22794.60',
    stock_qty: '62',
    experience: '2 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 40,
    avatar: '4.jpg',
    category: 'Hammad Condell',
    parent_category: 'Project Manager',
    email: 'hcondell13@tiny.cc',
    city: 'Bulung’ur',
    start_date: '11/04/2018',
    salary: '$10872.83',
    stock_qty: '37',
    experience: '7 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 41,
    avatar: '',
    category: 'Parker Bice',
    parent_category: 'Technical Writer',
    email: 'pbice14@ameblo.jp',
    city: 'Shanlian',
    start_date: '03/02/2016',
    salary: '$17471.92',
    stock_qty: '65',
    experience: '5 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 42,
    avatar: '',
    category: 'Lowrance Orsi',
    parent_category: 'Biostatistician',
    email: 'lorsi15@wp.com',
    city: 'Dengteke',
    start_date: '12/10/2018',
    salary: '$24719.51',
    stock_qty: '64',
    experience: '4 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 43,
    avatar: '10.jpg',
    category: 'Ddene Chaplyn',
    parent_category: 'Environmental Tech',
    email: 'dchaplyn16@nymag.com',
    city: 'Lattes',
    start_date: '01/23/2019',
    salary: '$11958.33',
    stock_qty: '38',
    experience: '8 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 44,
    avatar: '',
    category: 'Washington Bygraves',
    parent_category: 'Human Resources Manager',
    email: 'wbygraves17@howstuffworks.com',
    city: 'Zlaté Hory',
    start_date: '09/07/2016',
    salary: '$10552.43',
    stock_qty: '37',
    experience: '7 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 45,
    avatar: '7.jpg',
    category: 'Meghann Bodechon',
    parent_category: 'Operator',
    email: 'mbodechon18@1und1.de',
    city: 'Itō',
    start_date: '07/23/2018',
    salary: '$23024.28',
    stock_qty: '61',
    experience: '1 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 46,
    avatar: '1.jpg',
    category: 'Moshe De Ambrosis',
    parent_category: 'Recruiting Manager',
    email: 'mde19@purevolume.com',
    city: 'San Diego',
    start_date: '02/10/2018',
    salary: '$10409.90',
    stock_qty: '47',
    experience: '7 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 47,
    avatar: '5.jpg',
    category: 'Had Chatelot',
    parent_category: 'Cost Accountant',
    email: 'hchatelot1a@usatoday.com',
    city: 'Mercedes',
    start_date: '11/23/2016',
    salary: '$11446.30',
    stock_qty: '64',
    experience: '4 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 48,
    avatar: '',
    category: 'Georgia McCrum',
    parent_category: 'Registered Nurse',
    email: 'gmccrum1b@icio.us',
    city: 'Nggalak',
    start_date: '04/19/2018',
    salary: '$14002.31',
    stock_qty: '63',
    experience: '3 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 49,
    avatar: '8.jpg',
    category: 'Krishnah Stilldale',
    parent_category: 'VP Accounting',
    email: 'kstilldale1c@chronoengine.com',
    city: 'Slavs’ke',
    start_date: '03/18/2017',
    salary: '$10704.29',
    stock_qty: '56',
    experience: '6 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 50,
    avatar: '4.jpg',
    category: 'Mario Umbert',
    parent_category: 'Research Assistant',
    email: 'mumbert1d@digg.com',
    city: 'Chorotis',
    start_date: '05/13/2019',
    salary: '$21813.54',
    stock_qty: '43',
    experience: '3 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 51,
    avatar: '',
    category: 'Edvard Dixsee',
    parent_category: 'Graphic Designer',
    email: 'edixsee1e@unblog.fr',
    city: 'Rancharia',
    start_date: '04/23/2019',
    salary: '$18053.11',
    stock_qty: '46',
    experience: '6 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 52,
    avatar: '9.jpg',
    category: 'Tammie Davydoch',
    parent_category: 'VP Quality Control',
    email: 'tdavydoch1f@examiner.com',
    city: 'Mamedkala',
    start_date: '04/19/2016',
    salary: '$17617.08',
    stock_qty: '47',
    experience: '7 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 53,
    avatar: '',
    category: 'Benito Rodolico',
    parent_category: 'Safety Technician',
    email: 'brodolico1g@sciencedirect.com',
    city: 'Wonosobo',
    start_date: '10/06/2018',
    salary: '$18866.55',
    stock_qty: '21',
    experience: '1 Year',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 54,
    avatar: '',
    category: 'Marco Pennings',
    parent_category: 'Compensation Analyst',
    email: 'mpennings1h@bizjournals.com',
    city: 'Umag',
    start_date: '06/15/2017',
    salary: '$13722.18',
    stock_qty: '30',
    experience: '0 Year',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 55,
    avatar: '',
    category: "Tommie O'Corr",
    parent_category: 'Quality Engineer',
    email: 'tocorr1i@nyu.edu',
    city: 'Olhos de Água',
    start_date: '09/26/2018',
    salary: '$15228.80',
    stock_qty: '51',
    experience: '1 Year',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 56,
    avatar: '1.jpg',
    category: 'Cybill Poyle',
    parent_category: 'Cost Accountant',
    email: 'cpoyle1j@amazon.com',
    city: 'Hamm',
    start_date: '01/03/2016',
    salary: '$13951.96',
    stock_qty: '29',
    experience: '9 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 57,
    avatar: '6.jpg',
    category: 'Norry Stoller',
    parent_category: 'Human Resources Manager',
    email: 'nstoller1k@noaa.gov',
    city: 'Ruukki',
    start_date: '02/04/2018',
    salary: '$15100.00',
    stock_qty: '27',
    experience: '7 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 58,
    avatar: '',
    category: 'Wendi Somerlie',
    parent_category: 'Systems Administrator',
    email: 'wsomerlie1l@accuweather.com',
    city: 'Meicheng',
    start_date: '04/22/2016',
    salary: '$20023.52',
    stock_qty: '28',
    experience: '9 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 59,
    avatar: '',
    category: 'Ferdie Georgeon',
    parent_category: 'Geologist',
    email: 'fgeorgeon1m@nhs.uk',
    city: 'Tanahbeureum',
    start_date: '04/08/2019',
    salary: '$12630.26',
    stock_qty: '28',
    experience: '1 Year',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 60,
    avatar: '',
    category: 'Jules Auten',
    parent_category: 'Desktop Support Technician',
    email: 'jauten1n@foxnews.com',
    city: 'Mojo',
    start_date: '08/13/2019',
    salary: '$13870.62',
    stock_qty: '48',
    experience: '5 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 61,
    avatar: '3.jpg',
    category: 'Nichole Dacres',
    parent_category: 'Mechanical Systems Engineer',
    email: 'ndacres1o@apache.org',
    city: 'Kimanuit',
    start_date: '11/06/2017',
    salary: '$18220.51',
    stock_qty: '20',
    experience: '0 Year',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 62,
    avatar: '1.jpg',
    category: 'Holly Edgworth',
    parent_category: 'Junior Executive',
    email: 'hedgworth1p@craigslist.org',
    city: 'Pedreira',
    start_date: '08/05/2017',
    salary: '$13999.88',
    stock_qty: '37',
    experience: '0 Year',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 63,
    avatar: '9.jpg',
    category: 'Henriette Croft',
    parent_category: 'Food Chemist',
    email: 'hcroft1q@desdev.cn',
    city: 'Taizhou',
    start_date: '09/12/2019',
    salary: '$11049.79',
    stock_qty: '53',
    experience: '1 Year',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 64,
    avatar: '',
    category: 'Annetta Glozman',
    parent_category: 'Staff Accountant',
    email: 'aglozman1r@storify.com',
    city: 'Pendawanbaru',
    start_date: '08/25/2017',
    salary: '$10745.32',
    stock_qty: '27',
    experience: '3 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 65,
    avatar: '',
    category: 'Cletis Cervantes',
    parent_category: 'Health Coach',
    email: 'ccervantes1s@de.vu',
    city: 'Solnechnyy',
    start_date: '05/24/2018',
    salary: '$24769.08',
    stock_qty: '22',
    experience: '7 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 66,
    avatar: '9.jpg',
    category: 'Christos Kiley',
    parent_category: 'Geologist',
    email: 'ckiley1t@buzzfeed.com',
    city: 'El Bolsón',
    start_date: '02/27/2019',
    salary: '$16053.15',
    stock_qty: '46',
    experience: '2 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 67,
    avatar: '7.jpg',
    category: 'Silvain Siebert',
    parent_category: 'VP Sales',
    email: 'ssiebert1u@domainmarket.com',
    city: 'Cadiz',
    start_date: '09/23/2017',
    salary: '$23347.17',
    stock_qty: '47',
    experience: '8 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 68,
    avatar: '',
    category: 'Sharla Ibberson',
    parent_category: 'Payment Adjustment Coordinator',
    email: 'sibberson1v@virginia.edu',
    city: 'Lamam',
    start_date: '11/01/2016',
    salary: '$15658.40',
    stock_qty: '51',
    experience: '8 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 69,
    avatar: '7.jpg',
    category: 'Ripley Rentcome',
    parent_category: 'Physical Therapy Assistant',
    email: 'rrentcome1w@youtu.be',
    city: 'Dashkawka',
    start_date: '07/15/2018',
    salary: '$15396.66',
    stock_qty: '41',
    experience: '8 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 70,
    avatar: '',
    category: 'Chrisse Birrane',
    parent_category: 'Chemical Engineer',
    email: 'cbirrane1x@google.com.br',
    city: 'Las Toscas',
    start_date: '05/22/2016',
    salary: '$15823.40',
    stock_qty: '62',
    experience: '0 Year',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 71,
    avatar: '',
    category: 'Georges Tesyro',
    parent_category: 'Human Resources Manager',
    email: 'gtesyro1y@last.fm',
    city: 'Gabao',
    start_date: '01/27/2019',
    salary: '$19051.25',
    stock_qty: '37',
    experience: '7 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 72,
    avatar: '',
    category: 'Bondon Hazard',
    parent_category: 'Geological Engineer',
    email: 'bhazard1z@over-blog.com',
    city: 'Llano de Piedra',
    start_date: '01/17/2019',
    salary: '$11632.84',
    stock_qty: '65',
    experience: '3 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 73,
    avatar: '5.jpg',
    category: 'Aliza MacElholm',
    parent_category: 'VP Sales',
    email: 'amacelholm20@printfriendly.com',
    city: 'Sosnovyy Bor',
    start_date: '11/17/2017',
    salary: '$16741.31',
    stock_qty: '64',
    experience: '7 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 74,
    avatar: '2.jpg',
    category: 'Lucas Witherdon',
    parent_category: 'Senior Quality Engineer',
    email: 'lwitherdon21@storify.com',
    city: 'Staré Křečany',
    start_date: '09/26/2016',
    salary: '$19387.76',
    stock_qty: '38',
    experience: '2 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 75,
    avatar: '',
    category: 'Pegeen Peasegod',
    parent_category: 'Web Designer',
    email: 'ppeasegod22@slideshare.net',
    city: 'Keda',
    start_date: '05/21/2016',
    salary: '$24014.04',
    stock_qty: '59',
    experience: '6 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 76,
    avatar: '',
    category: 'Elyn Watkinson',
    parent_category: 'Structural Analysis Engineer',
    email: 'ewatkinson23@blogspot.com',
    city: 'Osan',
    start_date: '09/30/2016',
    salary: '$14493.51',
    stock_qty: '55',
    experience: '7 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 77,
    avatar: '10.jpg',
    category: 'Babb Skirving',
    parent_category: 'Analyst Programmer',
    email: 'bskirving24@cbsnews.com',
    city: 'Balky',
    start_date: '09/27/2016',
    salary: '$24733.28',
    stock_qty: '39',
    experience: '1 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 78,
    avatar: '',
    category: 'Shelli Ondracek',
    parent_category: 'Financial Advisor',
    email: 'sondracek25@plala.or.jp',
    city: 'Aoluguya Ewenke Minzu',
    start_date: '03/28/2016',
    salary: '$21922.17',
    stock_qty: '23',
    experience: '1 Year',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 79,
    avatar: '9.jpg',
    category: 'Stanislaw Melloy',
    parent_category: 'Sales Associate',
    email: 'smelloy26@fastcompany.com',
    city: 'Funafuti',
    start_date: '04/13/2017',
    salary: '$16944.42',
    stock_qty: '30',
    experience: '2 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 80,
    avatar: '',
    category: 'Seamus Eisikovitsh',
    parent_category: 'Legal Assistant',
    email: 'seisikovitsh27@usgs.gov',
    city: 'Cangkringan',
    start_date: '05/28/2018',
    salary: '$21963.69',
    stock_qty: '22',
    experience: '7 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 81,
    avatar: '2.jpg',
    category: 'Tammie Wattins',
    parent_category: 'Web Designer',
    email: 'twattins28@statcounter.com',
    city: 'Xilin',
    start_date: '08/07/2018',
    salary: '$16049.93',
    stock_qty: '36',
    experience: '5 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 82,
    avatar: '8.jpg',
    category: 'Aila Quailadis',
    parent_category: 'Technical Writer',
    email: 'aquail29@prlog.org',
    city: 'Shuangchahe',
    start_date: '02/11/2018',
    salary: '$24137.29',
    stock_qty: '43',
    experience: '4 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 83,
    avatar: '',
    category: 'Myrvyn Gilogly',
    parent_category: 'Research Associate',
    email: 'mgilogly2a@elpais.com',
    city: 'Prince Rupert',
    start_date: '05/13/2018',
    salary: '$10089.96',
    stock_qty: '19',
    experience: '8 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 84,
    avatar: '5.jpg',
    category: 'Hanna Langthorne',
    parent_category: 'Analyst Programmer',
    email: 'hlangthorne2b@stumbleupon.com',
    city: 'Guaynabo',
    start_date: '11/11/2018',
    salary: '$14227.10',
    stock_qty: '21',
    experience: '7 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 85,
    avatar: '',
    category: 'Ruby Gimblet',
    parent_category: 'Registered Nurse',
    email: 'rgimblet2c@1688.com',
    city: 'Nanyulinxi',
    start_date: '03/28/2016',
    salary: '$19562.59',
    stock_qty: '30',
    experience: '1 Year',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 86,
    avatar: '4.jpg',
    category: 'Louis Paszak',
    parent_category: 'Programmer',
    email: 'lpaszak2d@behance.net',
    city: 'Chiscas',
    start_date: '04/25/2016',
    salary: '$17178.86',
    stock_qty: '51',
    experience: '7 Years',
    num_of_products: 5
  },
  {
    responsive_id: '',
    id: 87,
    avatar: '',
    category: 'Glennie Riolfi',
    parent_category: 'Computer Systems Analyst',
    email: 'griolfi2e@drupal.org',
    city: 'Taung',
    start_date: '06/18/2018',
    salary: '$15089.83',
    stock_qty: '29',
    experience: '4 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 88,
    avatar: '',
    category: 'Jemimah Morgan',
    parent_category: 'Staff Accountant',
    email: 'jmorgan2f@nifty.com',
    city: 'La Esperanza',
    start_date: '01/17/2016',
    salary: '$18330.72',
    stock_qty: '27',
    experience: '3 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 89,
    avatar: '10.jpg',
    category: 'Talya Brandon',
    parent_category: 'Food Chemist',
    email: 'tbrandon2g@ucoz.com',
    city: 'Zaječar',
    start_date: '10/08/2018',
    salary: '$16284.64',
    stock_qty: '28',
    experience: '6 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 90,
    avatar: '6.jpg',
    category: 'Renate Shay',
    parent_category: 'Recruiter',
    email: 'rshay2h@tumblr.com',
    city: 'Pueblo Viejo',
    start_date: '03/15/2017',
    salary: '$18523.75',
    stock_qty: '28',
    experience: '3 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 91,
    avatar: '',
    category: 'Julianne Bartosik',
    parent_category: 'Senior Cost Accountant',
    email: 'jbartosik2i@state.gov',
    city: 'Botlhapatlou',
    start_date: '02/06/2017',
    salary: '$17607.66',
    stock_qty: '48',
    experience: '6 Years',
    num_of_products: 3
  },
  {
    responsive_id: '',
    id: 92,
    avatar: '3.jpg',
    category: 'Yvonne Emberton',
    parent_category: 'Recruiter',
    email: 'yemberton2j@blog.com',
    city: 'Nagcarlan',
    start_date: '02/13/2017',
    salary: '$17550.18',
    stock_qty: '20',
    experience: '1 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 93,
    avatar: '8.jpg',
    category: 'Danya Faichnie',
    parent_category: 'Social Worker',
    email: 'dfaichnie2k@weather.com',
    city: 'Taling',
    start_date: '07/29/2019',
    salary: '$18469.35',
    stock_qty: '37',
    experience: '3 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 94,
    avatar: '',
    category: 'Ronica Hasted',
    parent_category: 'Software Consultant',
    email: 'rhasted2l@hexun.com',
    city: 'Gangkou',
    start_date: '07/04/2019',
    salary: '$24866.66',
    stock_qty: '53',
    experience: '7 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 95,
    avatar: '2.jpg',
    category: 'Edwina Ebsworth',
    parent_category: 'Human Resources Assistant',
    email: 'eebsworth2m@sbwire.com',
    city: 'Puzi',
    start_date: '09/27/2018',
    salary: '$19586.23',
    stock_qty: '27',
    experience: '2 Years',
    num_of_products: 1
  },
  {
    responsive_id: '',
    id: 96,
    avatar: '',
    category: 'Alaric Beslier',
    parent_category: 'Tax Accountant',
    email: 'abeslier2n@zimbio.com',
    city: 'Ocucaje',
    start_date: '04/16/2017',
    salary: '$19366.53',
    stock_qty: '22',
    experience: '8 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 97,
    avatar: '',
    category: 'Reina Peckett',
    parent_category: 'Quality Control Specialist',
    email: 'rpeckett2o@timesonline.co.uk',
    city: 'Anyang',
    start_date: '05/20/2018',
    salary: '$16619.40',
    stock_qty: '46',
    experience: '8 Years',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 98,
    avatar: '7.jpg',
    category: 'Olivette Gudgin',
    parent_category: 'Paralegal',
    email: 'ogudgin2p@gizmodo.com',
    city: 'Fujinomiya',
    start_date: '04/09/2019',
    salary: '$15211.60',
    stock_qty: '47',
    experience: '8 Years',
    num_of_products: 2
  },
  {
    responsive_id: '',
    id: 99,
    avatar: '10.jpg',
    category: 'Evangelina Carnock',
    parent_category: 'Cost Accountant',
    email: 'ecarnock2q@washington.edu',
    city: 'Doushaguan',
    start_date: '01/26/2017',
    salary: '$23704.82',
    stock_qty: '51',
    experience: '0 Year',
    num_of_products: 4
  },
  {
    responsive_id: '',
    id: 100,
    avatar: '',
    category: 'Glyn Giacoppo',
    parent_category: 'Software Test Engineer',
    email: 'ggiacoppo2r@apache.org',
    city: 'Butha-Buthe',
    start_date: '04/15/2017',
    salary: '$24973.48',
    stock_qty: '41',
    experience: '7 Years',
    num_of_products: 2
  }
]

mock.onGet('/api/datatables/initial-data').reply(config => {
  return [200, data]
})

mock.onGet('/api/datatables/data').reply(config => {
  // eslint-disable-next-line object-curly-newline
  const { q = '', perPage = 10, page = 1 } = config
  /* eslint-enable */

  const queryLowered = q.toLowerCase()
  const filteredData = data.filter(
    item =>
      /* eslint-disable operator-linebreak, implicit-arrow-linebreak */
      item.category.toLowerCase().includes(queryLowered) ||
      item.parent_category.toLowerCase().includes(queryLowered) ||
      item.email.toLowerCase().includes(queryLowered) ||
      item.stock_qty.toLowerCase().includes(queryLowered) ||
      item.salary.toLowerCase().includes(queryLowered) ||
      item.start_date.toLowerCase().includes(queryLowered)
  )
  /* eslint-enable  */

  return [
    200,
    {
      allData: data,
      invoices: paginateArray(filteredData, perPage, page),
      total: filteredData.length
    }
  ]
})
